import type { NextConfig } from "next";

/**
 * Development only. Everything below is about being able to regenerate an asset
 * and actually see it; none of it should reach a deployed build.
 */
const dev = process.env.NODE_ENV !== "production";

const nextConfig: NextConfig = {
  // ~/Projects/moje has a stray package.json and package-lock.json at the top
  // level, and Turbopack walks upward looking for a workspace root — so without
  // this it adopts the parent directory and warns on every start.
  turbopack: { root: __dirname },

  images: {
    /**
     * Bypass the image optimizer while developing.
     *
     * Next 16 raised `minimumCacheTTL` from 60 seconds to 4 hours, and the
     * optimizer has no invalidation: its own docs say to change the `src` or
     * delete `<distDir>/cache/images` by hand. Every image in this project is
     * generated by a script and iterated on under a fixed filename — cards from
     * the scans, the LOSOWA card — so that default means a regenerated asset is
     * invisible for four hours and no reload can help.
     *
     * Unoptimized, `<Image>` serves the file itself, which carries a
     * Last-Modified that changes the moment a script rewrites it.
     */
    unoptimized: dev,
  },

  async headers() {
    if (!dev) return [];
    // The optimizer's cache is keyed on the upstream response, and these are
    // the two trees that scripts/ rewrite in place. Documented approach: set
    // Cache-Control on the asset itself, never on /_next/image.
    const noStore = [{ key: "Cache-Control", value: "no-store, must-revalidate" }];
    return [
      { source: "/cards/:file*", headers: noStore },
      { source: "/music/:file*", headers: noStore },
    ];
  },
};

export default nextConfig;
