/** Turns the transcribed JSON into literal-union id types the compiler can check. */

import fs from "node:fs";

/**
 * The board can express its ids as a type because it is written in TypeScript;
 * the cards and characters cannot, because they are JSON and TypeScript widens
 * every string it imports from one to `string`.
 *
 * So the ids are written out here as const tuples. Not a second source of truth
 * — `ids.test.ts` asserts these are exactly what the JSON holds, so a stale
 * file fails the build rather than silently letting a renamed card through.
 *
 * Run after anything that changes the transcription:
 *   node scripts/generate-ids.mjs
 */
const read = (path) => JSON.parse(fs.readFileSync(path, "utf8"));

const unique = (ids) => [...new Set(ids)].sort();

const characters = unique(read("src/data/characters.json").map((c) => c.id));
const events = unique(read("src/data/events.json").map((c) => c.id));
const items = unique(read("src/data/items.json").map((i) => i.id));
const spells = unique(read("src/data/spells.json").map((s) => s.id));

const tuple = (name, ids, doc) =>
  `${doc}\nexport const ${name} = [\n${ids.map((id) => `  "${id}",`).join("\n")}\n] as const;\n`;

const out = `/** Generated by scripts/generate-ids.mjs — do not edit. Checked by ids.test.ts. */

${tuple(
  "CHARACTER_IDS",
  characters,
  `/** The 27 Karty Postaci. */`,
)}
export type CharacterId = (typeof CHARACTER_IDS)[number];

${tuple(
  "EVENT_IDS",
  events,
  `/**
 * Every distinct Karta Zdarzeń. Distinct, not every card: the deck holds real
 * printed duplicates and they share an id.
 */`,
)}
export type EventId = (typeof EVENT_IDS)[number];

${tuple("ITEM_IDS", items, `/** The Wyposażenie pile. */`)}
export type ItemId = (typeof ITEM_IDS)[number];

${tuple("SPELL_IDS", spells, `/** The Karty Zaklęć. */`)}
export type SpellId = (typeof SPELL_IDS)[number];

/**
 * Anything a character can be holding or a field can be carrying.
 *
 * Rule 16.6 makes a drawn Magiczny Miecz and the Wyposażenie card the same
 * card, so the two id spaces genuinely overlap and this is a union rather than
 * a discriminated pair.
 */
export type CardId = EventId | ItemId | SpellId;

/**
 * The doors a \`string\` comes through to become one of these.
 *
 * Everything written inside the app names cards and characters by literal, and
 * the compiler checks those against the lists above. A value that arrived from
 * somewhere else — a request body, a database column, a card named by a player
 * typing — is not one of them until it has been looked at, and this is where
 * that happens rather than at every use.
 */
const SETS = {
  character: new Set<string>(CHARACTER_IDS),
  event: new Set<string>(EVENT_IDS),
  item: new Set<string>(ITEM_IDS),
  spell: new Set<string>(SPELL_IDS),
};

export function isCharacterId(value: string | null | undefined): value is CharacterId {
  return value != null && SETS.character.has(value);
}

export function isEventId(value: string | null | undefined): value is EventId {
  return value != null && SETS.event.has(value);
}

export function isItemId(value: string | null | undefined): value is ItemId {
  return value != null && SETS.item.has(value);
}

export function isSpellId(value: string | null | undefined): value is SpellId {
  return value != null && SETS.spell.has(value);
}

export function isCardId(value: string | null | undefined): value is CardId {
  return isEventId(value) || isItemId(value) || isSpellId(value);
}
`;

fs.writeFileSync("src/data/ids.ts", out);
console.log(
  `src/data/ids.ts: ${characters.length} characters, ${events.length} events, ` +
    `${items.length} items, ${spells.length} spells`,
);
