/** Writes src/lib/engine/content/index.ts: every Karta file under content/, imported and listed. */

import fs from "node:fs";
import path from "node:path";

/**
 * The index is generated for the same reason `ids.ts` is: one file per Karta
 * is the point (docs/KARTA.md step 3), and a hand-kept list of two hundred
 * imports is the file somebody forgets. `content.test.ts` fails the build when
 * this is stale, exactly as `ids.test.ts` does for the ids.
 *
 * Run after adding, removing or renaming a Karta file:
 *   node scripts/generate-cards.mjs
 */
const ROOT = "src/lib/engine/content";

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    // `shared/` holds fragments several Karty import (a wish, a table); nothing in it is a Karta.
    if (entry.isDirectory()) {
      if (entry.name !== "shared") out.push(...walk(full));
    }
    else if (entry.name.endsWith(".ts") && !entry.name.endsWith(".test.ts") && entry.name !== "index.ts") {
      out.push(full);
    }
  }
  return out;
}

const files = walk(ROOT).map((full) => path.relative(ROOT, full).replace(/\.ts$/, "").split(path.sep).join("/"));

const nameOf = (rel) => rel.replace(/[^a-zA-Z0-9]+/g, "_");

const lines = [
  "/** Generated by scripts/generate-cards.mjs — do not edit. Checked by content.test.ts. */",
  "",
  'import type { Karta } from "../karta";',
  ...files.map((rel) => `import ${nameOf(rel)} from "./${rel}";`),
  "",
  "/** Every Karta in the box, one file each, in path order. */",
  "export const KARTY: readonly Karta[] = [",
  ...files.map((rel) => `  ${nameOf(rel)},`),
  "];",
  "",
];

fs.writeFileSync(path.join(ROOT, "index.ts"), lines.join("\n"));
console.log(`content/index.ts: ${files.length} Karty`);
