/** Generated by scripts/generate-cards.mjs — do not edit. Checked by content.test.ts. */

import type { Karta } from "../karta";
import stranger_eremita from "./stranger/eremita";

/** Every Karta in the box, one file each, in path order. */
export const KARTY: readonly Karta[] = [
  stranger_eremita,
];
