/** Generated by scripts/generate-ids.mjs — do not edit. Checked by ids.test.ts. */

/** The 27 Karty Postaci. */
export const CHARACTER_IDS = [
  "awanturnik",
  "barbarzynca",
  "bledny-rycerz",
  "czarodziej",
  "demon",
  "elf",
  "goblin",
  "hobgoblin",
  "hummit",
  "kaplan",
  "kaplanka",
  "karzel",
  "kat",
  "krasnolud",
  "ksiaze",
  "lotr",
  "mag",
  "magog",
  "obbol",
  "olbrzym",
  "pustelnik",
  "quark",
  "rycerz-ciemnosci",
  "spryciarz",
  "troll",
  "wiedzma",
  "zdobywca",
] as const;

export type CharacterId = (typeof CHARACTER_IDS)[number];

/**
 * Every distinct Karta Zdarzeń. Distinct, not every card: the deck holds real
 * printed duplicates and they share an id.
 */
export const EVENT_IDS = [
  "1-sztuka-zlota",
  "2-sztuki-zlota",
  "alchemik",
  "arondight",
  "bojowy-rumak",
  "burza-siedmiu-slonc",
  "chochlik",
  "cudotworca",
  "cyklop",
  "czarna-hybryda",
  "czarodziej",
  "czarodziejska-kosc",
  "czerwona-hybryda",
  "danina",
  "demon",
  "diament-krolow",
  "dobre-bostwo",
  "drzewo-zycia",
  "duch-ciemnosci",
  "duch-zaglady",
  "dziki-rumak",
  "elflin",
  "eliksir-sily",
  "eremita",
  "excalibur",
  "fomoraig",
  "giermek",
  "gliniana-tabliczka",
  "gnom",
  "godzina-duchow",
  "grota",
  "hadron",
  "helm",
  "jablko-natchnienia",
  "jednorozec",
  "jezioro-magiczne",
  "kapliczka-nemed",
  "kapliczka-tolimana",
  "kij-i-sznur",
  "kometa",
  "kon",
  "koszmar",
  "krol-lasu",
  "krysztal-losu",
  "krysztal-magow",
  "krzyzowiec",
  "ksiaze-demonow",
  "ksiezniczka",
  "kuglarz",
  "labirynt",
  "latarnia",
  "lewiatan",
  "lodz",
  "los",
  "magiczna-sakwa",
  "magiczna-tablica",
  "magiczny-manuskrypt",
  "magiczny-miecz",
  "medrzec",
  "mgla",
  "miecz",
  "miecz-chaosu",
  "mul",
  "najemnik",
  "niedzwiedz",
  "nieznana-swiatynia",
  "nobbin",
  "opiekun",
  "owoc-jarzebiny-wiedzy",
  "pasterz",
  "pierscien-mocy",
  "polbog",
  "poludnica",
  "poslancy-bogow",
  "poszukiwacz-przygod",
  "przesilenie",
  "przewodnik",
  "przewoznika",
  "przybysz-z-krainy-cieni",
  "rekawice",
  "relikwiarz",
  "rozdzka-przeznaczenia",
  "rozdzka-zaklec",
  "rusalka",
  "rycerz",
  "sabat-czarownic",
  "sidh",
  "skalne-wrota",
  "slup-ognia",
  "smok",
  "sniezne-monstrum",
  "sobowtor",
  "spalona-ziemia",
  "srebrna-strzala",
  "straz",
  "strzyga",
  "swieta-wlocznia",
  "swiety-graal",
  "sztukmistrz",
  "sztylet",
  "tajemna-sakwa",
  "tajemne-przejscie",
  "tajemnicza-szkatula",
  "talizman-ognia",
  "talizman-powietrza",
  "tarcza",
  "tarcza-boga-tolimana",
  "targowisko",
  "topor-swiatla-i-ciemnosci",
  "tragarz",
  "trogglowy-smok",
  "turniej-rycerski",
  "uklad-planet",
  "upior",
  "urocza-diablica",
  "wampir",
  "wedrowiec",
  "widmo",
  "wielkolud",
  "wierzchowiec",
  "wilk",
  "wilkolak",
  "wladca",
  "wrozka",
  "zacmienie-slonc",
  "zakleta-sciezka",
  "zaklete-zrodlo",
  "zaklinacz-czasu",
  "zaprzeg",
  "zaraza",
  "zasadzka",
  "zatrute-ziola",
  "zbroja",
  "zjawa",
  "zloczynca",
  "zlodziej-dobroczynca",
  "zly-duch",
  "zwierciadlo-zniszczenia",
] as const;

export type EventId = (typeof EVENT_IDS)[number];

/** The Wyposażenie pile. */
export const ITEM_IDS = [
  "helm",
  "kij-i-sznur",
  "kon",
  "latarnia",
  "lodz",
  "magiczny-miecz",
  "miecz",
  "rekawice",
  "sztylet",
  "tarcza",
  "tarcza-tolimana",
  "zbroja",
] as const;

export type ItemId = (typeof ITEM_IDS)[number];

/** The Karty Zaklęć. */
export const SPELL_IDS = [
  "fatum",
  "formula-czasu",
  "formula-przestrzeni",
  "golem",
  "homunculus",
  "kamien-filozoficzny",
  "krag-plomieni",
  "magia-i-miecz",
  "magiczna-wedrowka",
  "ocalony",
  "odmiana-losu",
  "odrodzenie",
  "olsnienie",
  "pan-bogactwa",
  "pan-przyjaciol",
  "pan-trzesawisk",
  "powiew-smierci",
  "siedem-wichrow",
  "siewca-spustoszenia",
  "szalenstwo",
  "wladca-czarow",
  "wladca-gromu",
  "wladca-lodu",
  "wladca-zaklec",
  "wladca-zdarzen",
  "wojna-zywiolow",
  "zwierciadlo",
] as const;

export type SpellId = (typeof SPELL_IDS)[number];

/**
 * Anything a character can be holding or a field can be carrying.
 *
 * Rule 16.6 makes a drawn Magiczny Miecz and the Wyposażenie card the same
 * card, so the two id spaces genuinely overlap and this is a union rather than
 * a discriminated pair.
 */
export type CardId = EventId | ItemId | SpellId;

/**
 * The doors a `string` comes through to become one of these.
 *
 * Everything written inside the app names cards and characters by literal, and
 * the compiler checks those against the lists above. A value that arrived from
 * somewhere else — a request body, a database column, a card named by a player
 * typing — is not one of them until it has been looked at, and this is where
 * that happens rather than at every use.
 */
const SETS = {
  character: new Set<string>(CHARACTER_IDS),
  event: new Set<string>(EVENT_IDS),
  item: new Set<string>(ITEM_IDS),
  spell: new Set<string>(SPELL_IDS),
};

export function isCharacterId(value: string | null | undefined): value is CharacterId {
  return value != null && SETS.character.has(value);
}

export function isEventId(value: string | null | undefined): value is EventId {
  return value != null && SETS.event.has(value);
}

export function isItemId(value: string | null | undefined): value is ItemId {
  return value != null && SETS.item.has(value);
}

export function isSpellId(value: string | null | undefined): value is SpellId {
  return value != null && SETS.spell.has(value);
}

export function isCardId(value: string | null | undefined): value is CardId {
  return isEventId(value) || isItemId(value) || isSpellId(value);
}
